version: "3.3"
services: 
    web:
        container_name: hello
        build: .
        image: node:8
        command: node index.js
        ports:
            - "3001:5000"
        networks: 
            - test
    redis:
        
networks: 
    test:
        driver: bridge
    test2:
        driver: bridge